# Generated by Django 3.0.7 on 2020-06-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparelho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do aparelho')),
                ('slug', models.SlugField(default='', editable=False, max_length=100, verbose_name='Atalho')),
                ('quantidade', models.IntegerField(blank=True, default=1, verbose_name='Quantidade')),
                ('potencia', models.IntegerField(blank=True, null=True, verbose_name='Potencia em watts')),
                ('tempo', models.IntegerField(blank=True, null=True, verbose_name='Tempo de uso')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'minutos/dia'), (2, 'horas/dia')], default=2, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'aparelho',
                'verbose_name_plural': 'Aparelho',
                'db_table': 'aparelho',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do ambiente')),
                ('slug', models.SlugField(default='', editable=False, max_length=100, verbose_name='Atalho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aparelhos', models.ManyToManyField(blank=True, db_table='aparelho_ambiente', related_name='aparelhos_no_ambiente', to='consumo_de_energia.Aparelho', verbose_name='Selecione os aparelhos')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'db_table': 'ambiente',
                'ordering': ['name'],
            },
        ),
    ]
